version: '3'

services:
  # Database
  nuxtpress.mysql:
    container_name: ${NUXTPRESS_MYSQL_CONTAINER:-nuxtpress.mysql}
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${NUXTPRESS_MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${NUXTPRESS_DB_NAME:-wordpress}
      MYSQL_USER: ${NUXTPRESS_MYSQL_USER:-xwordpress}
      MYSQL_PASSWORD: ${NUXTPRESS_MYSQL_PASSWORD:-xwordpress}
    # if switch to just using .env file
    # env_file:
    #   - ./env/db.env
    networks:
      - wpsite

  # phpmyadmin
  nuxtpress.phpmyadmin:
    container_name: ${NUXTPRESS_PHPMYADMIN_CONTAINER:-nuxtpress.phpmyadmin}
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - nuxtpress.mysql
    ports:
      - '8080:80'
    environment:
      PMA_HOST: ${NUXTPRESS_MYSQL_CONTAINER:-nuxtpress.mysql}
      MYSQL_ROOT_PASSWORD: ${NUXTPRESS_MYSQL_ROOT_PASSWORD:-password}
    networks:
      - wpsite

  # Wordpress
  nuxtpress.wp:
    container_name: ${NUXTPRESS_WP_CONTAINER:-nuxtpress.wp}
    image: wordpress:5.8.2-php7.4-apache
    depends_on:
      - ${NUXTPRESS_MYSQL_CONTAINER:-nuxtpress.mysql}
    restart: always
    ports:
      - '${NUXTPRESS_WP_PORT:-3080}:80'
    volumes:
      - ./backend/wp-content:/var/www/html/wp-content
    environment:
      NUXTPRESS_WP_PORT: ${NUXTPRESS_WP_PORT:-3080}
      WORDPRESS_DB_HOST: ${NUXTPRESS_DB_HOST:-nuxtpress.mysql:3306}
      WORDPRESS_DB_USER: ${NUXTPRESS_DB_USER:-xwordpress}
      WORDPRESS_DB_PASSWORD: ${NUXTPRESS_DB_PASSWORD:-xwordpress}
      WORDPRESS_DB_NAME: ${NUXTPRESS_DB_NAME:-wordpress}
    networks:
      - wpsite

  # Nuxt2
  # This is turned off by default
  # Nuxt spins up a development server much faster "npm run dev".
  # Switch back on production ready
  # nuxtpress.front:
  #   container_name: ${NUXTPRESS_NUXT_CONTAINER:-nuxtpress.front}
  #   image: node:12-slim
  #   working_dir: '/var/www/nuxtpress-app'
  #   ports:
  #     - '${NUXTPRESS_NUXT_PORT:-3000}:3000'
  #   volumes:
  #     - ./frontend:/var/www/nuxtpress-app
  #   environment:
  #     HOST: 0.0.0.0
  #     NUXTPRESS_WP_CONTAINER: ${NUXTPRESS_WP_CONTAINER:-nuxtpress.wp}
  #     NUXTPRESS_WP_URL: ${NUXTPRESS_WP_URL:-http://localhost:3080}
  #     NUXTPRESS_WP_PORT: ${NUXTPRESS_WP_PORT:-3080}
  #   command: bash -c "npm install && npm run dev"
  #   networks:
  #     - wpsite

networks:
  wpsite:
volumes:
  db_data:
  wp-content:
